In [1]:
import pandas as pd
import numpy as np


In [10]:
df=pd.read_csv('dataset\Recommed.csv',header=None)
df.columns=["User_id","Movie_id","Rating","Timestamp"]

In [11]:
df.head(10)

User_id  Movie_id  Rating  Timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596
5      298       474       4  884182806
6      115       265       2  881171488
7      253       465       5  891628467
8      305       451       3  886324817
9        6        86       3  883603013

In [12]:
from sklearn.model_selection import train_test_split
n_users=df.User_id.unique().shape[0]
n_movies=df.Movie_id.unique().shape[0]
train_data,test_data=train_test_split(df,test_size=0.25)


In [13]:
train_data_matrix=np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [14]:
test_data_matrix=np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
from sklearn.metrics import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')
movie_similarity=pairwise_distances(train_data_matrix.T,metric="cosine")
mean_user_rating=train_data_matrix.mean(axis=1)[:,np.newaxis]
rating_diff=(train_data_matrix-mean_user_rating)
user_pred=mean_user_rating+user_similarity.dot(rating_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.53617379,  0.56727191,  0.47785001, ...,  0.28498024,
         0.28742212,  0.28713499],
       [ 1.27361571,  0.30095027,  0.17427559, ..., -0.04871347,
        -0.04557629, -0.04518848],
       [ 1.27482127,  0.23952915,  0.12398521, ..., -0.10338867,
        -0.10024826, -0.09998792],
       ...,
       [ 1.14399566,  0.20802532,  0.09084344, ..., -0.12437102,
        -0.12134947, -0.12118503],
       [ 1.30780623,  0.29036296,  0.19451004, ..., -0.02697527,
        -0.02423581, -0.02388182],
       [ 1.36259422,  0.37178684,  0.30058282, ...,  0.10430358,
         0.10654628,  0.10687434]])